apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tplValue" ( dict "value" .Values.global.commonLabels "context" . ) | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-function
  namespace: {{ .Release.Namespace }}
  labels:
    serverless.kyma-project.io/config: service-account
automountServiceAccountToken: false
imagePullSecrets:
  - name: {{ template "fullname" . }}-registry-config
  - name: {{ template "fullname" . }}-registry-config-default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-build
  namespace: {{ .Release.Namespace }}
  labels:
    serverless.kyma-project.io/config: service-account
---
apiVersion: v1                             
kind: ServiceAccount                         
metadata:
  name: {{ template "fullname" . }}-kpack               
  namespace: {{ .Release.Namespace }}
  labels:
    serverless.kyma-project.io/config: service-account                 
secrets:                                     
- name: {{ template "fullname" . }}-registry-config-default
